name: ice_code_editor
version: 0.0.11
description: Code Editor + Preview
authors:
- Chris Strom <chris@eeecomputes.com>
- Santiago Arias <santiago.ariassar@gmail.com>
- Srdjan Pejic <spejic@gmail.com>
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  crypto: any
  js: any
  ctrl_alt_foo: any
  json: any
  polymer: {path: /home/chris/repos/dart/dart/pkg/polymer}
dev_dependencies:
  scheduled_test: any
